### PR TITLE
new Binding function, bug fixes in EAN and BAC classes

### PR DESCRIPTION
**Pull request by UnleashedGH**

### CODE REVIEW

**Comment by LazyBone152** [comment]
I'm confused about the edit to Uninstall.cs. What is the problem there?

**Comment by UnleashedGH** [comment]
> I'm confused about the edit to Uninstall.cs. What is the problem there?

when Reinstalling BAC files (i specifically tried that on Non-CPK ones) the SortID will be duplicated for the entries and the BAC's Deserializer class will raise exception

**Comment by LazyBone152** [comment]
The BAC installer seems to be broken, that's probably the root cause of the issue.

A few months ago I updated the code to not require all bac entry IDs to be sequential and allow gaps in the IDs, it would just add in all missing entries while saving. But the installer still expects it to work the old way and needs to be updated.

**Comment by LazyBone152** [comment]
It should be fixed with the latest commit. Can you try it?

**Comment by UnleashedGH** [comment]
> It should be fixed with the latest commit. Can you try it?

tried with 2 Non-CPK BACs and checked after Reinstall, all good

**Pull request merged**
